name: flutter_les_emirs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  socket_io_client: ^3.1.2
  flutter_riverpod: ^3.0.0
  riverpod: ^3.0.0
  go_router: ^16.2.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  easy_localization: ^3.0.8
  flutter_dotenv: ^6.0.0
  file_picker: ^8.2.0
  url_launcher: ^6.3.1
  flutter_window_close: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  freezed: ^2.5.8
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - .env